//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.EF_DataModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_OS_SISTEMASEntities : DbContext
    {
        public DB_OS_SISTEMASEntities()
            : base("name=DB_OS_SISTEMASEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_DEPARTAMENTO> TB_DEPARTAMENTO { get; set; }
        public virtual DbSet<TB_DESENVOLVEDORES> TB_DESENVOLVEDORES { get; set; }
        public virtual DbSet<TB_LOGON_SISTEMA> TB_LOGON_SISTEMA { get; set; }
        public virtual DbSet<TB_PRIORIDADE_ITEM> TB_PRIORIDADE_ITEM { get; set; }
        public virtual DbSet<TB_PROJETO_DESENVOLVEDORES> TB_PROJETO_DESENVOLVEDORES { get; set; }
        public virtual DbSet<TB_PROJETO_DESENVOLVIMENTO> TB_PROJETO_DESENVOLVIMENTO { get; set; }
        public virtual DbSet<TB_PROJETO_ITENS> TB_PROJETO_ITENS { get; set; }
        public virtual DbSet<TB_PROJETOS_SISTEMAS> TB_PROJETOS_SISTEMAS { get; set; }
        public virtual DbSet<TB_STATUS_DESENVOLVIMENTO> TB_STATUS_DESENVOLVIMENTO { get; set; }
        public virtual DbSet<TB_TIPO_DESENVOLVIMENTO> TB_TIPO_DESENVOLVIMENTO { get; set; }
        public virtual DbSet<TB_TIPO_USUARIO> TB_TIPO_USUARIO { get; set; }
        public virtual DbSet<TB_USUARIOS> TB_USUARIOS { get; set; }
        public virtual DbSet<TB_ITENS_FINALIZADOS> TB_ITENS_FINALIZADOS { get; set; }
        public virtual DbSet<TB_PROJETOS_FINALIZADOS> TB_PROJETOS_FINALIZADOS { get; set; }
    }
}
