//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.EF_DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ITENS_FINALIZADOS
    {
        public int ID { get; set; }
        public Nullable<int> ID_ITEM { get; set; }
        public Nullable<int> ID_NM_SOLICITACAO { get; set; }
        public Nullable<System.DateTime> DT_FINALIZADO { get; set; }
        public Nullable<int> ID_DESENVOLVEDOR_ITEM { get; set; }
        public string ID_USUARIO_LOGADO { get; set; }
    
        public virtual TB_DESENVOLVEDORES TB_DESENVOLVEDORES { get; set; }
        public virtual TB_PROJETO_ITENS TB_PROJETO_ITENS { get; set; }
        public virtual TB_PROJETO_DESENVOLVIMENTO TB_PROJETO_DESENVOLVIMENTO { get; set; }
    }
}
