//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.EF_DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_LOGON_SISTEMA
    {
        public int ID_LOGIN { get; set; }
        public Nullable<int> ID_USUARIO { get; set; }
        public Nullable<System.DateTime> DT_LOGON { get; set; }
        public Nullable<bool> FL_USUARIO_LOGADO { get; set; }
    
        public virtual TB_USUARIOS TB_USUARIOS { get; set; }
    }
}
