//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.EF_DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PROJETO_ITENS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_PROJETO_ITENS()
        {
            this.TB_ITENS_FINALIZADOS = new HashSet<TB_ITENS_FINALIZADOS>();
        }
    
        public int ID_ITEM { get; set; }
        public Nullable<int> ID_NM_SOLICITACAO { get; set; }
        public string NOME_SOLICITANTE { get; set; }
        public Nullable<int> ID_DEPARTAMENTO { get; set; }
        public Nullable<System.DateTime> DT_ABERTURA { get; set; }
        public string DESCRICAO { get; set; }
        public Nullable<int> ID_DEV { get; set; }
        public Nullable<int> ID_TIPO_DESENV { get; set; }
        public Nullable<int> ID_STATUS { get; set; }
        public string CAMADAS_METODOS_DESCRICAO { get; set; }
        public string PROCEDURES_NOMES { get; set; }
        public string DESCRICAO_DESENVOLVIMENTO { get; set; }
        public Nullable<System.DateTime> DT_TERMINO { get; set; }
        public Nullable<bool> FL_COMMIT_ITEM { get; set; }
        public Nullable<System.TimeSpan> TOTAL_HRS_ITEM { get; set; }
        public Nullable<bool> FL_ITEM_ENCERRADO { get; set; }
        public Nullable<System.DateTime> DT_PUBLICACAO { get; set; }
        public Nullable<int> ID_PRIORIDADE { get; set; }
    
        public virtual TB_DEPARTAMENTO TB_DEPARTAMENTO { get; set; }
        public virtual TB_DESENVOLVEDORES TB_DESENVOLVEDORES { get; set; }
        public virtual TB_PROJETO_DESENVOLVIMENTO TB_PROJETO_DESENVOLVIMENTO { get; set; }
        public virtual TB_STATUS_DESENVOLVIMENTO TB_STATUS_DESENVOLVIMENTO { get; set; }
        public virtual TB_TIPO_DESENVOLVIMENTO TB_TIPO_DESENVOLVIMENTO { get; set; }
        public virtual TB_PRIORIDADE_ITEM TB_PRIORIDADE_ITEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ITENS_FINALIZADOS> TB_ITENS_FINALIZADOS { get; set; }
    }
}
