//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.EF_DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_USUARIOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_USUARIOS()
        {
            this.TB_DESENVOLVEDORES = new HashSet<TB_DESENVOLVEDORES>();
            this.TB_LOGON_SISTEMA = new HashSet<TB_LOGON_SISTEMA>();
        }
    
        public int ID_USUARIO { get; set; }
        public string NOME { get; set; }
        public Nullable<int> ID_DEPARTAMENTO { get; set; }
        public string EMAIL { get; set; }
        public string LOGIN { get; set; }
        public string SENHA { get; set; }
        public Nullable<System.DateTime> DT_CADASTRO { get; set; }
        public Nullable<int> ID_TIPO_USUARIO { get; set; }
        public Nullable<bool> FL_ATIVO { get; set; }
        public Nullable<bool> FL_DESENVOLVEDOR { get; set; }
        public Nullable<System.DateTime> DT_ALTERACAO { get; set; }
        public byte[] IMG_PERFIL { get; set; }
    
        public virtual TB_DEPARTAMENTO TB_DEPARTAMENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_DESENVOLVEDORES> TB_DESENVOLVEDORES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_LOGON_SISTEMA> TB_LOGON_SISTEMA { get; set; }
        public virtual TB_TIPO_USUARIO TB_TIPO_USUARIO { get; set; }
    }
}
